import "~~/styles/globals.css";
// import { ThemeProvider } from "~~/components/ThemeProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning>
      <body>
        {/* <ThemeProvider enableSystem> */}
          {children}
          {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
