import React from "react";
import "~~/styles/globals.css";

// import { ThemeProvider } from "~~/components/ThemeProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning>
      <body>
        <div className=" text-gray-800 flex items-center flex-col bg-red-100 h-screen">
          <div className="bg-white/80 rounded-full pt-12 pb-10 px-10 w-[600px] flex items-center justify-center font-serif">
            <h1 className="text-4xl ">💋 De Dating Sims 🎮</h1>
          </div>
          {/* <ThemeProvider enableSystem> */}
          {children}
          {/* </ThemeProvider> */}
        </div>
      </body>
    </html>
  );
}
